pcdshub/pcdswidgets

.gitignore
examples/show_icon.py
pcdswidgets/icons/__init__.py
pcdswidgets/icons/base.py
pcdswidgets/icons/gauges.py
pcdswidgets/icons/others.py
pcdswidgets/icons/pumps.py
pcdswidgets/icons/valves.py
pcdswidgets/symbols/__init__.py
pcdswidgets/symbols/base.py
pcdswidgets/symbols/gauges.py
pcdswidgets/symbols/mixins.py
pcdswidgets/symbols/others.py
pcdswidgets/symbols/pumps.py
pcdswidgets/symbols/valves.py
tests/symbols/test_base.py
tests/symbols/test_mixins.py
tests/symbols/test_symbols.py
tests/test_designer.py
tests/test_icons.py
tests/test_smoke.py

I wanted to move and rename a things in this repo so figured I'd lay down a first round of tests just to check for any regressions. Locally this gets me up to about 90% but that number is pretty inflated as a lot of these are just smoke tests. We can go back through with a more thorough comb as features are expanded.

Basic Testing Suite

---

tests/test_icons.py

This seems to solve #6. Thanks @hhslepicka !
Closes #6

TST: Wait for widget to be visible for paintEvent

---

.travis.yml

Strip out old xvfb setup in favor of a Travis service

CI: Install xvfb as a service

---

pcdswidgets/icons/base.py
tests/test_icons.py

Add a `clicked` signal to `BaseSymbolIcon`

Clickable Icons

---

pcdswidgets/vacuum/gauges.py
pcdswidgets/vacuum/pumps.py
pcdswidgets/vacuum/valves.py

FIX: Readback PVs need to follow PyTMC conventions

---

pcdswidgets/vacuum/gauges.py
pcdswidgets/vacuum/pumps.py

Change displayFormat at labels to use Exponential.
Request from users to make it better to visualize values.
Locally
Nowhere.

ENH: Switch some widgets readback label to Exponential format.

---

pcdswidgets/vacuum/pumps.py

Changing the Ion Pump state PV prefix as requested by @ghalym 
Closes https://github.com/pcdshub/pcdswidgets/issues/31

FIX: Update Ion Pump state PV suffix.

---

pcdswidgets/utils.py
pcdswidgets/vacuum/base.py

Refactor the way we show the expert screens.
This code depends on a Typhos PR that will come up soon.
Make the code simpler.
Closes https://github.com/pcdshub/pcdswidgets/issues/33 and https://github.com/pcdshub/pcdswidgets/issues/32
This PR depends on https://github.com/pcdshub/typhos/pull/245 and https://github.com/pcdshub/pcdsutils/pull/4

REF: Refactor to move functions to places where it makes more sense.

---

pcdswidgets/vacuum/base.py

Keep internal cache for the expert screen of a certain device and if it is already open just bring it to front.
Keep a reference to the screen so it does not get garbage collected
This should fix https://github.com/pcdshub/lucid/issues/44
Locally

FIX: Cache expert displays and fix loose reference.

---

pcdswidgets/vacuum/gauges.py

Change RoughGauge state PV from PRESS_OK_RBV to STATE_RBV.
Closes #43 
Locally
N/A

FIX: Change RoughGauge state PV from PRESS_OK_RBV to STATE_RBV.

---

pcdswidgets/vacuum/base.py
pcdswidgets/vacuum/valves.py

- Fix a bug when trying to set the class name for a widget
- Update the FastShutter expert screen class as requested by @slacAdpai 
Fix a bug and update the class to the newly created one.

FIX: Bug at ophydExpertClass setter and update class for FastShutter

---

pcdswidgets/vacuum/valves.py

DEV: updated Fastshutter's error_suffix to STATE_RBV in valve.py

---

docs/source/mixins.rst
pcdswidgets/vacuum/mixins.py
pcdswidgets/vacuum/valves.py

- Add a new mixing MultipleButtonControl
- Change FastShutter to use this new mixin.
Closes #48 
Locally
New documentation entry added.

ENH: New Mixin MultipleButtonControl and FastShutter buttons

---

pcdswidgets/vacuum/gauges.py

DOC: fixes typo in docstring of HotCathodeGauge class.

---

docs/source/icons.rst
docs/source/vacuum/valves.rst
pcdswidgets/designer.py
pcdswidgets/icons/__init__.py
pcdswidgets/icons/valves.py
pcdswidgets/vacuum/valves.py

Normally Open Pneumatic Valve Widget
Closes #59 
Locally
Documentation was included in this Pull Request

ENH: Normally Open Pneumatic Valve Widget

---

docs/Makefile

Generate icons before issuing Sphinx command.
Attempt to solve the issue at #62 
Locally
N/A

DOC: Generate figures before making the docs.

---

.travis.yml
conda-recipe/meta.yaml

Update to latest CI standards.
Closes #61 
With PYPI_TOKEN now set, we can deploy to PyPI as well.

CI: update to latest standards

---

docs/source/conf.py
docs/source/dev.rst
docs/source/index.rst

Add a short documentation page explaining the steps to setup a development environment for pcdswidgets.
Pcdswidgets is slightly more complex to install in a development environment because it requires an environment variable to be set before the widgets can be accessed in designer. This step was not apparent from the existing documentation so I thought it should be added. 
Having followed these steps, my environment works. 
This is a documentation PR.

Add developer docs

---

.pre-commit-config.yaml
docs/source/addwidget.rst
docs/source/icons.rst
docs/source/index.rst
docs/source/vacuum/valves.rst
pcdswidgets/designer.py
pcdswidgets/icons/__init__.py
pcdswidgets/icons/demo/__main__.py
pcdswidgets/icons/valves.py
pcdswidgets/vacuum/__init__.py
pcdswidgets/vacuum/demo/__main__.py
pcdswidgets/vacuum/valves.py

Valve with no default position. When losing air/power, it stays where it is. It requires active control to open or close. This has implications for the interlocking.
Icon so far:
Three of these valves are in RIX
https://jira.slac.stanford.edu/browse/LCLSPC-338
Interactively only
Added a page detailing my journey to make a new widget
Add the new widget to the general widget docs

ENH: Dual-acting valve

---

.github/workflows/standard.yml

Enabling GitHub Actions for pcdshub/pcdswidgets.
Not to be reviewed in-depth - #80 will be where fixes and comments go.
This will not be tested as-is.

CI: add standard GitHub Actions CI workflow

---

.pre-commit-config.yaml

Update the pre-commit versions in hopes of removing the false-positive CI failure in #93 
https://github.com/pcdshub/pcdswidgets/actions/runs/14407873575/job/40408710502?pr=93
If the CI passes, it was good enough
We can put this in the release notes

MNT: pre-commit autoupdate
