pcdswidgets/vacuum/base.py
Came across this issue when I tried to demonstrate the widgets to someone.
It happens because at the QtDesigner we add the BaseWidget for the enums to work properly.
This change is required so we avoid issues when someone does not define an icon to be used with a symbol.
Locally.
Nowhere.
=> FIX: Avoid issues when no Icon is set.

pcdswidgets/vacuum/base.py, pcdswidgets/vacuum/others.py, pcdswidgets/vacuum/pumps.py, pcdswidgets/vacuum/valves.py
Today after updating my code and using Qt newer than 5.6 I started having problems to load the widgets. I narrowed it down to the fact that properties for the widgets were returning None.
I believe that Qt no longer likes it.
Locally since we can't test QtDesigner at CI.
N/A
=> FIX: QtDesigner started to present issues with properties returning None

docs/source/icons.rst, docs/source/vacuum/valves.rst, pcdswidgets/designer.py, pcdswidgets/icons/__init__.py, pcdswidgets/icons/valves.py, pcdswidgets/vacuum/valves.py
Created widgets for `ControlValve`, `ControlOnlyValveNC` and `ControlOnlyValveNO`. I only got a screenshot of one thing for the controls only valve so for now both NC and NO have the same icon.
=> Control Valves

pcdswidgets/vacuum/base.py, pcdswidgets/vacuum/gauges.py, pcdswidgets/vacuum/others.py, pcdswidgets/vacuum/pumps.py, pcdswidgets/vacuum/valves.py, tests/vacuum/test_base.py, tests/vacuum/test_mixins.py
Icons were being created before the widgets resulting in windows without parent that were floating around. This caused a massive flickering effect when opening the designer via XForwarding.
Fix the issue above which is annoying.
Tested locally.
=> FIX: Avoid flickering icon windows by creating icons with parents = self.

pcdswidgets/icons/pumps.py, pcdswidgets/vacuum/gauges.py, pcdswidgets/vacuum/mixins.py, pcdswidgets/vacuum/pumps.py, pcdswidgets/vacuum/valves.py
- Valves now have a PV to describe the State. Before it was a logical combination of Open and Close status PVs.
- Added a property to control the controlButton orientation on a per widget basis. This allow for more flexibility and positioning when creating screens.
- Request from users
- Locally
Nowhere.
=> Change state valves

pcdswidgets/icons/base.py, pcdswidgets/utils.py, pcdswidgets/vacuum/base.py
ENH: PV Prefix in general widget tooltip.
ENH: Middle click on icons shows State PV and copy to clipboard.
Attn. @slacAdpai @slacAWallace 
Address most of the issues from #27.
=> ENH: Tooltip and other fixes

pcdswidgets/utils.py, pcdswidgets/vacuum/base.py, pcdswidgets/vacuum/gauges.py, pcdswidgets/vacuum/pumps.py, pcdswidgets/vacuum/valves.py
Added `OPHYD_CLASS` class attribute to widget classes.
This new attribute can be a string or a class that will be used alongside with the `channelPrefix` to create a `TyphosDeviceDisplay` as an expert screen.
Request from users.
Locally.
Attn. @slacAdpai @slacAWallace @sfsyunusSLAC
=> ENH: Added icon click handler to open TyphosDeviceDisplay as an expert screen.

pcdswidgets/vacuum/base.py
The if statement was returning True even if layout was a valid object and causing a layout to be set at the `interlock` frame all the time without first removing the old layout.
Fix to remove the annoying message:
```
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
```
=> FIX: Fix the layout setup for widgets.

pcdswidgets/vacuum/base.py, pcdswidgets/vacuum/gauges.py, pcdswidgets/vacuum/pumps.py, pcdswidgets/vacuum/valves.py
This PR adds a new property called `ophydClass` at `PCDSSymbolBase` that will allow users to opt-out of the default suggested Ophyd Device class to be used for the expert screen.
This is a change requested by @n-wbrown .
Tests are passing.
=> ENH: Add new property ophydClass at BaseWidget

pcdswidgets/vacuum/mixins.py
Makes the EnumButtons non-checkable. This way the buttons will not present the state and cause confusion.
Request from @slacAWallace and @ghalym 
Locally
This PR depends on the following PyDM PR: https://github.com/slaclab/pydm/pull/614
=> ENH: Make EnumButtons not checkable.

pcdswidgets/icons/valves.py, pcdswidgets/vacuum/valves.py
Adds a new property into the FastShutter icon widget called `arrowBrush` which allow users to customize the brush to paint the arrow area or inverted Christmas three (🤷‍♂️ ).
Attn. @slacAdpai 
Closes #46 
Locally.
Docs update to include new property.
=> ENH: FastShutter Arrow color

pcdswidgets/icons/base.py, pcdswidgets/icons/valves.py
Increases the arrow at the FastShutter Icon as requested by @slacAdpai 
Closes #52 
Locally
Before:
After:
=> ENH: Make arrow bigger for FastShutter valve icon.

pcdswidgets/icons/valves.py, pcdswidgets/vacuum/mixins.py
FIX: Revert debug green color at FastShutter arrow_brush leftover from test.
DOC: Fix identation at MultipleButton mixin.
=> FIX: Leftover debug color and fix docs

pcdswidgets/vacuum/base.py
When a Vacuum widget has an expert screen associated with it, the Cursor now changes in the same way as the PyDM Related Display button.
Requested by Silke. Closes #57 
Locally.
N/A
With mouse over and having an expert screen:
=> ENH: Add custom cursor similar to RelatedDisplayButton for icon with expert screen.

README.md, dev-requirements.txt
Remove codecov. We aren't using it and they had a security breach
=> MNT: remove codecov after recent security breach

.travis.yml, examples/basic_table.json, examples/basic_table.py, examples/basic_table.ui, examples/basic_table_row.ui, pcdswidgets/designer.py, pcdswidgets/table.py
Add the `FilterSortWidgetTable` widget. This widget allows us to repeat a template generically in a table form, and handle things like sorting and filtering in a re-usable way.
Here's a screenshot of the TMO screen I am working on that uses this widget:
Features:
This is a common motif and we should be able to re-use it in multiple contexts
Only interactiveley so far
Only docstrings so far
=> ENH: add sortable/filterable table inspired by pmps-ui

pcdswidgets/icons/base.py
Force the setter here to store an `int` so that `setWidth` gets an `int`
The python 3.10 test suite fails on setWidth receiving floats.
Ran the test suite offline
N/A
=> MAINT: setWidth requires an int in py310

.pre-commit-config.yaml, pcdswidgets/vacuum/base.py
When device widget icon is pressed a predefined screen will appear as a tab in the typhos screen. If no screen is defined typhos works as usual.
Allows for more information to be displayed about a device, such as interlock information.
https://jira.slac.stanford.edu/browse/LCLSECSD-1735
Made a test screen that contains a pcds widget and checked the behavior when the icon is pressed. 
Tested variation of inputs in designer properties.
=> Allow for custom ui file to be open when widget icon is pressed.

pcdswidgets/eps_byteindicator.py
Widget for displaying EPS structure information as a ByteIndicator. The widget automatically sets the correct size and labels based on EPS structure PLC code, given the base PV of the EPS structure PV.
[Jira Ticket](https://jira.slac.stanford.edu/browse/LCLSPC-373)
Using a PLC program with the modified twincat-general and twincat-motion, a test program was written. The test program was ran on the tst-motion PLC and its associated IOC. Using these PVs the eps-widget was tested to see if the widget functioned as expected.
=> ENH: add eps widget for EPS PLC structure

pcdswidgets/table.py
One line change, switched order of active and filter_name paramters in activate_filter from table.py.
Currently, attempting to change the filter results in: TypeError: activate_filter() got multiple values for argument 'filter_name', presumably because filter_name is the first argument and is given by a keyword argument in the slot for the filter menu, but the pyqt gives the bool as the first positional argument, causing there to be multiple values for filter_name and none for active.
I think this is caused by the use of functools partial: the signal calls the partial object with one argument, but this is given as the first positional argument, which was already given in the creation of the object as a keyword argument. 
I made the change in my local repo and used pydm to create a window …
=> BUG fixing activate_filter by rearranging parameters to work with qtpy

docs-requirements.txt, docs/source/conf.py, pyproject.toml
* Support `pip install pcdswidgets[doc]`, for packaging purposes and CI/docs building purposes
* Updates documentation configuration (copyright, intersphinx config, package naming "PCDS Widgets" -> pcdswidgets)
* Fixes up miscellaneous build warning
Closes #86 
Closes #83 (bonus)
CI
This PR and the linked issue
=> BLD/FIX: support 'pip install .[doc]'

pyproject.toml
Add Qt designer entrypoint for byte indicator widget
Closes #88 
`from pcdswidgets.eps_byteindicator import EPSByteIndicator` works successfully
Issue #88
=> FIX: EPS byte indicator designer entrypoint

pcdswidgets/vacuum/valves.py
Changed  _interlock_suffix to ':OPN_OK_RBV' in FastShutter Class. 
Fast shutter valve Icon falsely displays a black border, indicating an interlock failure, but it is actually permitted to open. 
https://jira.slac.stanford.edu/browse/ECSENG-523
I used [sim-ioc](https://github.com/pcdshub/sim-ioc) to create a test IOC. Then created a test screen with the VFS icon. Changing the 'OPN_OK_RBV' PV changes the black boarder on the icon.
=> VFS Icon interlock bug

docs-requirements.txt
Adjusts the name of `docs_versions_menu` to use underscores so it matches conda, and doesn't break our env building scripts
I'm spending my time chasing an environment that doesn't want to be built
Zach showed that this should fix our extras gathering script independently.  On pip this shouldn't matter
This PR
=> BLD: adjust name of docs-versions-menu to match conda package name
